#!/usr/bin/env python3
"""Builds the Neighbors tab icon out of two copies of Material's location_city.

A New Yorker already lives in a building, so the Neighbors tab wants to read as a city rather than
as one more building. One location_city next to Home's apartment block looked, if anything, like
the smaller of the two. Two of them, scaled down and set side by side with the right one dropped
slightly so the skyline steps, reads as a city at 24dp.

Derived rather than drawn, so ic_location_city_24px.xml stays the single source: re-run this if
that icon is ever updated.

  python3 tools/artwork/cityscape.py
  python3 tools/artwork/rasterize.py mastodon/src/main/res/drawable/ic_city_of_cities_24px.xml
"""
import re

SOURCE = "mastodon/src/main/res/drawable/ic_location_city_24px.xml"
TARGET = "mastodon/src/main/res/drawable/ic_city_of_cities_24px.xml"

# location_city occupies x 120..840, y 80..840 on its 960 grid.
SCALE = 0.56
LEFT = (120, 300)    # where the left copy's own (120, 80) lands
RIGHT = (520, 380)   # the right copy, lower so the two skylines step rather than line up


def transform(data, scale, to_x, to_y, from_x=120.0, from_y=80.0):
    out = []
    for token in re.findall(r"[MLZ][^MLZ]*", data):
        cmd, rest = token[0], token[1:]
        if cmd == "Z":
            out.append("Z")
            continue
        x, y = (float(v) for v in rest.split(","))
        nx = x * scale + (to_x - from_x * scale)
        ny = y * scale + (to_y - from_y * scale)
        fmt = lambda v: str(int(v)) if float(v).is_integer() else f"{v:g}"
        out.append(f"{cmd}{fmt(nx)},{fmt(ny)}")
    return "".join(out)


def main():
    source = open(SOURCE).read()
    data = re.search(r'android:pathData="([^"]+)"', source).group(1)
    # Right first, left over the top, so the nearer cluster wins where they touch.
    combined = (transform(data, SCALE, *RIGHT) + transform(data, SCALE, *LEFT))
    open(TARGET, "w").write(
        '<!-- masto.nyc fork: the Neighbors tab. Two copies of Material\'s location_city, scaled\n'
        '     down and set side by side, so the tab reads as a city rather than as one more\n'
        '     building. Generated by tools/artwork/cityscape.py from ic_location_city_24px.xml,\n'
        '     which stays the single source; re-run that rather than editing this by hand. -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp"\n    android:height="24dp"\n'
        '    android:viewportWidth="960"\n    android:viewportHeight="960">\n'
        '  <path\n      android:fillColor="@android:color/white"\n'
        '      android:fillType="nonZero"\n'
        f'      android:pathData="{combined}"/>\n'
        '</vector>\n')
    print(f"{TARGET}: {len(combined)} chars of path data")


if __name__ == "__main__":
    main()
